# .goreleaser.yml
before:
  hooks:
    - go mod tidy

builds:
  - id: linux-build
    binary: slack-buddy
    ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
    - -extldflags=-static
    env:
    - CGO_ENABLED=1
    goos:
    - linux
    goarch:
    - amd64
    main: ./cmd/slack-buddy/main.go
  - id: darwin-build
    binary: slack-buddy
    ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
    env:
    - CGO_ENABLED=1
    - CC=/home/runner/work/osxcross/target/bin/o64-clang
    - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/slack-buddy/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

brews:
  - name: slack-buddy
    repository:
      owner: 'krzko'
      name: 'homebrew-tap'
    homepage: https://github.com/krzko/slack-buddy
    description: "Slack Buddy is a convenient tool designed to help you manage your Slack status effortlessly"
    install: |
      bin.install "slack-buddy"
    test: |
      system "#{bin}/slack-buddy -v"
