env:
  - GO111MODULE=on
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy

builds:
  - id: slack-buddy-darwin-amd64
    binary: slack-buddy
    main: ./cmd/slack-buddy
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
  - id: slack-buddy-darwin-arm64
    binary: slack-buddy
    main: ./cmd/slack-buddy
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
  - id: slack-buddy-linux-amd64
    binary: slack-buddy
    main: ./cmd/slack-buddy
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
      - -extldflags "-lc -lrt -lpthread --static"
  - id: slack-buddy-linux-arm64
    binary: slack-buddy
    main: ./cmd/slack-buddy
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
      - -extldflags "-lc -lrt -lpthread --static"
  - id: slack-buddy-windows-amd64
    binary: slack-buddy
    main: ./cmd/slack-buddy
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -buildmode=exe
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}

universal_binaries:
  - id: slack-buddy-darwin-universal
    ids:
      - slack-buddy-darwin-amd64
      - slack-buddy-darwin-arm64
    replace: true
    name_template: "slack-buddy"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

brews:
  - name: slack-buddy
    tap:
      owner: 'krzko'
      name: 'homebrew-tap'
    homepage: https://github.com/krzko/slack-buddy
    description: "Slack Buddy is a convenient tool designed to help you manage your Slack status effortlessly"
    install: |
      bin.install "slack-buddy"
    test: |
      system "#{bin}/slack-buddy -v"
