name: Release

on:
  push:
    tags:
      - '*'

env:
  GO_VERSION: "1.21"

jobs:
  release-darwin-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config .goreleaser-darwin.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install cross-compiler linux/arm64
        run: sudo apt-get -y install gcc-aarch64-linux-gnu

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --config .goreleaser-linux.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

  release-windows-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release  --config .goreleaser-windows.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
