name: Release

on:
  push:
    tags:
      - '*'

env:
  GO_VERSION: "1.21"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v5
      #   with:
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

      - name: Release dry run
        run: make release-dry-run

      - name: Seup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_TOKEN}}' > .release-env

      - name: Release publish
        run: make release